name: librenms

x-librenms-environment: &librenms-environment
  TZ: &TZ Europe/Paris
  PUID: &PUID "1000"
  PGID: &PGID "1000"
  DB_HOST: db
  DB_DATABASE: &DB_DATABASE librenms
  DB_USERNAME: &DB_USERNAME librenms
  DB_PASSWORD: &DB_PASSWORD asupersecretpassword
  DB_TIMEOUT: "60"
  CACHE_DRIVER: redis
  SESSION_DRIVER: redis
  REDIS_HOST: redis

services:
  db:
    image: mariadb:11.8
    container_name: librenms_db
    command:
      - "mariadbd"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      TZ: *TZ
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_DATABASE: *DB_DATABASE
      MARIADB_USER: *DB_USERNAME
      MARIADB_PASSWORD: *DB_PASSWORD
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    environment:
      TZ: *TZ
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: "587"
      SMTP_TLS: "on"
      SMTP_STARTTLS: "on"
      SMTP_TLS_CHECKCERT: "on"
      SMTP_AUTH: "on"
      SMTP_USER: foo
      SMTP_PASSWORD: bar
      SMTP_FROM: foo@gmail.com
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - redis
      - msmtpd
    volumes:
      - "./librenms:/data"
    environment:
      <<: *librenms-environment
    restart: always

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    environment:
      <<: *librenms-environment
      NODE_ID: dispatcher1
      SIDECAR_DISPATCHER: "1"
    restart: always

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      <<: *librenms-environment
      SIDECAR_SYSLOGNG: "1"
    restart: always

  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      <<: *librenms-environment
      SIDECAR_SNMPTRAPD: "1"
    restart: always
