#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# From https://github.com/docker-library/mariadb/blob/master/docker-entrypoint.sh#L21-L41
# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
  local var="$1"
  local fileVar="${var}_FILE"
  local def="${2:-}"
  if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
    echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
    exit 1
  fi
  local val="$def"
  if [ "${!var:-}" ]; then
    val="${!var}"
  elif [ "${!fileVar:-}" ]; then
    val="$(<"${!fileVar}")"
  fi
  export "$var"="$val"
  unset "$fileVar"
}

DB_PORT=${DB_PORT:-3306}
DB_DATABASE=${DB_DATABASE:-${DB_NAME:-librenms}}
DB_USERNAME=${DB_USERNAME:-${DB_USER:-librenms}}
DB_TIMEOUT=${DB_TIMEOUT:-60}

SIDECAR_DISPATCHER=${SIDECAR_DISPATCHER:-0}
SIDECAR_SYSLOGNG=${SIDECAR_SYSLOGNG:-0}
SIDECAR_SNMPTRAPD=${SIDECAR_SNMPTRAPD:-0}

# Persist only keys that must be shared by every container.
if [ "$SIDECAR_DISPATCHER" != "1" ] && [ "$SIDECAR_SYSLOGNG" != "1" ] && [ "$SIDECAR_SNMPTRAPD" != "1" ]; then
  exec 9>/data/.env.lock
  flock 9
  touch /data/.env
  sed -i '/^NODE_ID=/d' /data/.env

  if ! grep -q '^APP_KEY=' /data/.env; then
    echo "Generating APP_KEY"
    printf '\nAPP_KEY=%s\n' "$(artisan key:generate --no-interaction --force --show)" >>/data/.env
  fi

  if ! grep -q '^VAPID_PUBLIC_KEY=' /data/.env || ! grep -q '^VAPID_PRIVATE_KEY=' /data/.env; then
    echo "Generating VAPID keypair"
    sed '/^VAPID_\(PUBLIC\|PRIVATE\)_KEY=/d' /data/.env >"${LIBRENMS_PATH}/.env"
    chown librenms:librenms "${LIBRENMS_PATH}/.env"
    artisan webpush:vapid --no-interaction

    vapid_public_key="$(sed -n 's/^VAPID_PUBLIC_KEY=//p' "${LIBRENMS_PATH}/.env" | head -n 1)"
    vapid_private_key="$(sed -n 's/^VAPID_PRIVATE_KEY=//p' "${LIBRENMS_PATH}/.env" | head -n 1)"
    if [ -z "$vapid_public_key" ] || [ -z "$vapid_private_key" ]; then
      echo >&2 "ERROR: Failed to generate VAPID keypair"
      exit 1
    fi

    sed -i '/^VAPID_\(PUBLIC\|PRIVATE\)_KEY=/d' /data/.env
    printf '\nVAPID_PUBLIC_KEY=%s\nVAPID_PRIVATE_KEY=%s\n' "$vapid_public_key" "$vapid_private_key" >>/data/.env
  fi

  flock -u 9
else
  echo "Waiting ${DB_TIMEOUT}s for shared application keys..."
  counter=1
  while [ ! -f /data/.env ] ||
    ! grep -q '^APP_KEY=' /data/.env ||
    ! grep -q '^VAPID_PUBLIC_KEY=' /data/.env ||
    ! grep -q '^VAPID_PRIVATE_KEY=' /data/.env; do
    sleep 1
    counter=$((counter + 1))
    if [ "$counter" -gt "$DB_TIMEOUT" ]; then
      echo >&2 "ERROR: Shared application keys were not generated by the main container"
      exit 1
    fi
  done
fi

# NODE_ID belongs to this container and must not be persisted in the shared
# data-volume .env file.
existing_node_id="$(sed -n 's/^NODE_ID=//p' "${LIBRENMS_PATH}/.env" | head -n 1)"
if [ -n "${DISPATCHER_NODE_ID:-}" ]; then
  if [ -n "${NODE_ID:-}" ]; then
    echo >&2 "WARNING: DISPATCHER_NODE_ID is deprecated and ignored because NODE_ID is set"
  else
    echo >&2 "WARNING: DISPATCHER_NODE_ID is deprecated; use NODE_ID instead"
  fi
fi
node_id="${NODE_ID:-${DISPATCHER_NODE_ID:-${existing_node_id:-$(php -r 'echo bin2hex(random_bytes(16));')}}}"
sed '/^NODE_ID=/d' /data/.env >"${LIBRENMS_PATH}/.env"
printf '\nNODE_ID=%s\n' "$node_id" >>"${LIBRENMS_PATH}/.env"
export NODE_ID="$node_id"
printf '%s' "$NODE_ID" >/var/run/s6/container_environment/NODE_ID

chown librenms:librenms /data/.env "${LIBRENMS_PATH}/.env"
chmod 600 /data/.env "${LIBRENMS_PATH}/.env"

if [ "$SIDECAR_DISPATCHER" = "1" ] || [ "$SIDECAR_SYSLOGNG" = "1" ] || [ "$SIDECAR_SNMPTRAPD" = "1" ]; then
  exit 0
fi

file_env 'DB_PASSWORD'
if [ -z "$DB_PASSWORD" ]; then
  echo >&2 "ERROR: Either DB_PASSWORD or DB_PASSWORD_FILE must be defined"
  exit 1
fi

dbcmd="mariadb -h ${DB_HOST} -P ${DB_PORT} -u "${DB_USERNAME}" "-p${DB_PASSWORD}""
unset DB_PASSWORD

echo "Waiting ${DB_TIMEOUT}s for database to be ready..."
counter=1
while ! ${dbcmd} -e "show databases;" >/dev/null 2>&1; do
  sleep 1
  counter=$((counter + 1))
  if [ ${counter} -gt ${DB_TIMEOUT} ]; then
    echo >&2 "ERROR: Failed to connect to database on $DB_HOST"
    exit 1
  fi
done
echo "Database ready!"

# Enable first run wizard if db is empty
counttables=$(echo 'SHOW TABLES' | ${dbcmd} "$DB_DATABASE" | wc -l)
if [ "${counttables}" -eq "0" ]; then
  echo "Enabling First Run Wizard..."
  export INSTALL="user,finish"
  printf '%s' "$INSTALL" >/var/run/s6/container_environment/INSTALL
  printf 'env[INSTALL] = $INSTALL\n' >>/etc/php84/php-fpm.d/www.conf
fi

echo "Updating database schema..."
lnms migrate --force --no-ansi --no-interaction
artisan db:seed --force --no-ansi --no-interaction

echo "Clear cache"
artisan cache:clear --no-interaction
artisan config:cache --no-interaction

mkdir -p /etc/services.d/nginx
cat >/etc/services.d/nginx/run <<EOL
#!/usr/bin/execlineb -P
with-contenv
s6-setuidgid ${PUID}:${PGID}
nginx -g "daemon off;"
EOL
chmod +x /etc/services.d/nginx/run

mkdir -p /etc/services.d/php-fpm
cat >/etc/services.d/php-fpm/run <<EOL
#!/usr/bin/execlineb -P
with-contenv
s6-setuidgid ${PUID}:${PGID}
php-fpm84 -F
EOL
chmod +x /etc/services.d/php-fpm/run

mkdir -p /etc/services.d/snmpd
cat >/etc/services.d/snmpd/run <<EOL
#!/usr/bin/execlineb -P
with-contenv
/usr/sbin/snmpd -f -c /etc/snmp/snmpd.conf
EOL
chmod +x /etc/services.d/snmpd/run
